### ISSUE TITLE
Trouble setting up snare

### ISSUE THREAD

**Issue by abdulfatah-ah1407281** [mushorg/snare#170]
![screenshot from 2018-10-31 04-48-02](https://user-images.githubusercontent.com/25788910/47761122-4a204980-dcc8-11e8-8bc1-e10793d0b025.png)

Getting the following error when i try to run snare,

i ran 

> sudo snare --port 8080 --page-dir (page name here)

**Comment by afeena** [comment]
@abdulfatah-ah1407281 Hi :) Could you please check you meta.json file and tell me if something with status_404 is in this json? And also, have your cloning of the page finished properly or you cancelled it in some point?

**Comment by wangclin** [comment]
@afeena Hi :) After I cloned a interior website, I meet the same question. But the KeyError is 'hash'.  I've checked the meta.json file, but I don't find something wrong...
When I clone some open website, everything is ok. Is that a interior website question? Thx for your reply.

**Comment by afeena** [comment]
@wangclin Hi, could you please give me an idea how cloning page looks like? you have a domain address or you use localhost?

**Comment by wangclin** [comment]
@afeena Hi:)Thank you for your help. I don't know how to send pictures in comment.May I send a e-mail to you? A picture about my cloning page and snare page.Thank you again.

**Comment by DanielSpring** [comment]
> 
> 
> @afeena Hi:)Thank you for your help. I don't know how to send pictures in comment.May I send a e-mail to you? A picture about my cloning page and snare page.Thank you again.

Hi, Did you manage to get this issue sorted because I have exactly the same error messages? Thanks

**Comment by DanielSpring** [comment]
> 
> 
> ![screenshot from 2018-10-31 04-48-02](https://user-images.githubusercontent.com/25788910/47761122-4a204980-dcc8-11e8-8bc1-e10793d0b025.png)
> 
> Getting the following error when i try to run snare,
> 
> i ran
> 
> > sudo snare --port 8080 --page-dir (page name here)

Hi, did you manage to get this issue sorted out?

**Comment by wangclin** [comment]
@DanielSpring Not yet, I'm trying to solve it.

**Comment by DanielSpring** [comment]
@wangclin One thing i've found is the documentation is seriously lacking with Snare and Tanner. I managed to get it running where Snare wont produce any errors, this is only achived when a website is cloned from one hosted on your own local webserver.

There needs to be a Step-by-step guide on how to set the environment up from start to finish for testing and give real examples of attacks being performed. This is what beginners need.

**Comment by wangclin** [comment]
> @wangclin One thing i've found is the documentation is seriously lacking with Snare and Tanner. I managed to get it running where Snare wont produce any errors, this is only achived when a website is cloned from one hosted on your own local webserver.
> 
> There needs to be a Step-by-step guide on how to set the environment up from start to finish for testing and give real examples of attacks being performed. This is what beginners need.

Thank you for teaching. In fact, I've ran snare successfully under the guide .But when I cloned a private network web page, the snare showed a '404_status' error . It maybe a page trouble.

**Comment by subhazard** [comment]
I am also having this issue.

While free software is great, I don't know why people are so afraid of writing documentation that's more than a couple of half-assed sentences.

I don't know what your program is doing or supposed to be doing when you expect your users to read your mind.

**Comment by DanielSpring** [comment]
> 
> 
> I am also having this issue.
> 
> While free software is great, I don't know why people are so afraid of writing documentation that's more than a couple of half-assed sentences.
> 
> I don't know what your program is doing or supposed to be doing when you expect your users to read your mind.

lol I know tell me about it I've spent weeks upon end trying to get snare and tanner up and running properly still with no success. Whilst I did get then running, no results were showing after running a nikto scan. They stop for no reason when I visit tannerweb to inspect suuid, then I have to keep restarting them. What makes matters worse is Snare and Tanner are the only web-based honeypot of this type apart from Glastof in open-source community. That's why proper documentation should be top priority, especially when it comes to unique technologies such as these. People learning about Cyber Security can do so without spending a significant amount of time trying to troubleshoot these issues we're facing.

**Comment by glaslos** [comment]
Please keep in mind that all time invested by contributors in these projects is unpaid and besides our dayjobs. Our motivation to work on those projects comes from the appreciation from our users, collaboration with other contributors and most likely some personal interest in the topic. 
While I understand your frustration, I recommend to attempt to appeal to our motivation. Maybe create a pull request with some improvements to the README? Share your experience and suggest how we can make the project more accessible to new users.

**Comment by DanielSpring** [comment]
> 
> 
> Please keep in mind that all time invested by contributors in these projects is unpaid and besides our dayjobs. Our motivation to work on those projects comes from the appreciation from our users, collaboration with other contributors and most likely some personal interest in the topic.
> While I understand your frustration, I recommend to attempt to appeal to our motivation. Maybe create a pull request with some improvements to the README? Share your experience and suggest how we can make the project more accessible to new users.

Yes that's one thing I shall definiantly be doing, a full comprehensive installation guide. I really think this is important as it will save everybody some time in future in getting the environement up and running, especially students who are conducting research. Do you know where I could find the authors dissertation by any chance? I tried to look for it everywhere but couldn't find nothing, only a proposal on honeynet project.

**Comment by DanielSpring** [comment]
Oh ok, from looking at them documents I had seen, I though you was supervising someone on their final year project to add new features to Glastopf lol.

**Comment by subhazard** [comment]
I understand where you're coming from glaslos, but it is still disappointing to come across yet another project where there is insufficient documentation and has problems doing basic things it's meant to do. It doesn't look good for the open source community where the only motivation to make solid, comprehensible products is money.

**Comment by viskey98** [comment]
@subhazard I can understand your frustration, but this is a honeypot which is still in its growing stage and not that established. Moreover till the date (of this issue )we didn't face any issue telling us to improve the docs. All the issue that were created were solved by us and the users were pretty satisfied. So if you feel our project is lacking documentation, you need to let us know, instead of criticising it and all the work done by the contributors. Like @glaslos said, we contributors spend our precious time for this project apart from our everyday works. So if you feel disappointed, write your own documentation will all the full-assed explanation which satisfies you and make a PR. Till you get enough knowledge for the same, it doesn't sound nice to see you criticising not just our project but the whole open source community. :)

**Comment by viskey98** [comment]
@wangclin This is how you attach images to github issues: `copy the image (right click, Copy image) and then paste it into the text box where you describe the issue.`
As your problem is still not clear to me, I would suggest you to create a separate issue for your problem, including your images. :) 
I will do my best to fix it .

**Comment by viskey98** [comment]
@DanielSpring If you have this same problem create a new issue, because the author of this issue seems to be inactive. And at least you could have managed to respond to the questions asked by @afeena regarding this issue (which the author of this issue failed to respond). Without clarifications for those questions (asked by @afeena ) its difficult to sort out this problem. So better create a new issue on your side with the proper screenshots and details of the problem. 
I will do my best to fix it.

**Comment by glaslos** [comment]
I'm closing this issue as the original issue is fixed.

**Comment by DanielSpring** [comment]
@viskey98 Thanks for getting back to me, ok I shall bare that in mind for future reference.
